name: Nhat Inventory CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check Flake8
        run: docker-compose run app sh -c "flake8 ."
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - name: Run Django Test
        run: docker-compose run sh -c "python manage.py test"
