name: Nhat Inventory CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Compose
        run: docker-compose build
      - name: Check Flake8
        run: docker-compose run app sh -c "flake8 ."
      - name: Run Django Test
        run: docker-compose run app sh -c "python manage.py test"
      - name: Django Coverage action

